##############################################################
##                                 Logger and Server Config ##
##############################################################
spring.application.name=clouddm-console-application
logging.level.root=info
logging.level.org.springframework.boot.autoconfigure=ERROR
logging.file.path=${app.logPath}/
logging.file.name=${app.logPath}/console.log
logging.config=classpath:logback.xml
logging.file.max-size=200MB
logging.file.max-history=30
server.compression.enabled=true
server.compression.mime-types=application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
server.tomcat.mbeanregistry.enabled=true
spring.servlet.multipart.max-file-size=64MB
spring.servlet.multipart.max-request-size=64MB
spring.servlet.multipart.enabled=true
spring.cache.caffeine.spec=maximumSize=100000,expireAfterAccess=3600s
spring.cache.cache-names=rate-limit-buckets
spring.messages.basename=classpath:/static/i18n
spring.web.resources.static-locations=classpath:/templates
spring.main.allow-circular-references=true
##############################################################
##                                        DataSource Config ##
##############################################################
# default datasource
spring.datasource.connection-timeout=10000
spring.datasource.minimum-idle=1
spring.datasource.maximum-pool-size=20
spring.profiles.active=output
##############################################################
##                                              RDP Config  ##
##############################################################
clougence.rdp.console.csrf=false
clougence.rdp.console.default_product=CloudDM
clougence.rdp.deploy.env=output
clougence.rdp.console.enable_product_cluster=true
clougence.official.site.address=https://console.cdmgr.com
##############################################################
##                               CloudDM ds Config validate ##
##############################################################
clougence.rdp.dsconfig.validate.enable=false
##############################################################
##                                           CloudDM Config ##
##############################################################
clouddm.upgrade.server=f78aa36a.clougence.com
clouddm.consolejob.engine.async.threadpool=10
console.config.cross.origins=*
swagger.production=true